If running 'launch_docker' from WITHIN DOCKER, convert key paths to host paths to make volume mounts

diff --git a/script/launch_docker b/script/launch_docker
--- a/script/launch_docker
+++ b/script/launch_docker
@@ -106,23 +106,33 @@ flags_for_run(){
 }
 
 # Populate docker run env variable $BLJ_OPTIONS 
-# Always include vars to map Host paths: Config, $BLJ_PROJ, and $HOME.
+# Always include vars to map Host paths: Config, $BLJ_PROJ
 # In AWS mode, add a indicator, otherwise include the Host path for pipeline input. 
 # These paths are used by biolockj_controller to map Docker volumes for java_module containers
 blj_options() {
-	if in_docker_env && [ ${#BLJ_OPTIONS} -gt 0 ]; then # in docker container 
-		options="${BLJ_OPTIONS}"
-	else # on host machine
-		options="-projectDir ${BLJ_PROJ} -hostname $(hostname)"
-		ifArgUsed $GUI_ARG && echo "${options}" && return
-	fi	
-	ifDefined $restartDir && options="${options} -restartDir $restartDir"
+#	if in_docker_env && [ ${#BLJ_OPTIONS} -gt 0 ]; then # in docker container 
+#		options="${BLJ_OPTIONS}"
+#	else # on host machine
+#		options="-projectDir ${BLJ_PROJ}"
+#		ifArgUsed $GUI_ARG && echo "${options}" && return
+#	fi	
+    if in_docker_env ; then
+        options="-projectDir $(java -cp $BLJ/dist/BioLockJ.jar biolockj.util.DockerUtil ${BLJ_PROJ})"
+        ifDefined $restartDir && options="${options} -restartDir $(java -cp $BLJ/dist/BioLockJ.jar biolockj.util.DockerUtil $(to_abs_path $restartDir))"
+	else
+	    options="-projectDir ${BLJ_PROJ}"
+	    ifDefined $restartDir && options="${options} -restartDir $(to_abs_path $restartDir)"
+	fi
 	ifArgUsed $PASSWORD_ARG && options="${options} -password $newPass"
 	ifArgUsed $AWS_ARG && options="${options} -aws"
 	ifArgUsed $PRECHECK && options="${options} -precheck"
 	ifArgUsed $UNUSED_PROPS_ARG && ifArgUsed $PRECHECK && options="${options} -unusedProps"
 	ifArgUsed $UNUSED_PROPS_ARG && ! ifArgUsed $PRECHECK && options="${options} -precheck -unusedProps"
-	ifDefined $configFile && options="${options} -config $(to_abs_path ${configFile})"
+	if in_docker_env ; then
+	    ifDefined $configFile && options="${options} -config $(java -cp $BLJ/dist/BioLockJ.jar biolockj.util.DockerUtil $(to_abs_path ${configFile}) )"
+	else
+	    ifDefined $configFile && options="${options} -config $(to_abs_path ${configFile})"
+	fi
 	echo "${options}"
 }
 
@@ -145,9 +155,19 @@ get_volumes() {
 		else 
 			local i=1
 			readableConfig=$(get_readable_config)
-			# collec the output of read_config.  IFF that call has a non-0 exit, print any collected error messages.
-			configuredDirs=$(${BLJ}/script/read_config.sh "$readableConfig" "mount") 
+			# collect the output of read_config.  IFF that call has a non-0 exit, print any collected error messages.
+			#
+			#
+			configuredDirs=$(${BLJ}/script/read_config.sh "$readableConfig" "mount")
 			[ ! $? -eq 0 ] && echo "${configuredDirs[@]}" && exit 1 #this is called in subshell, failures have to get passed up the chain
+			#
+			#if in_docker_env ; then
+			#    configuredDirs=$(${BLJ}/script/biolockj-api listMounts --config $readableConfig)
+			#    [ ! $? -eq 0 ] && echo "Need to set up listMounts: ${configuredDirs[@]}" && exit 1 #this is called in subshell, failures have to get passed up the chain
+			#else
+			#	configuredDirs=$(${BLJ}/script/read_config.sh "$readableConfig" "mount")
+			#	[ ! $? -eq 0 ] && echo "${configuredDirs[@]}" && exit 1 #this is called in subshell, failures have to get passed up the chain
+			#fi
 			for dir in ${configuredDirs[@]}; do
 				vols="${vols} -v ${dir}:${EFS}/vol_${i}:ro" 
 				i=$(( i + 1 ))
